# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b2b0bc5a81a43417486f23dff2108a4e3ce3473d3ab93399a540c18a1621a3f5afd881a1f22032cbd8af381dde1fb6d83994f1470d2751ce9ade24d15dbbc8

test:
  secret_key_base: 9f94849c1f40752e401fd64e8ab0219792ce04ddd5fedc0c29748d616ed74696965c263cd9a0f1228389059a6db2fe382196bac62d54e75649289c679061d461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
